export const CATEGORIES = [
  "Lifestyle", "Fitness", "Health & Wellness", "Fashion", "Beauty", "Skincare",
  "Haircare", "Makeup", "Travel", "Food & Cooking", "Parenting", "Family",
  "Home Décor", "Interior Design", "Minimalism", "Sustainability", "Luxury Lifestyle",
  "Self-Improvement", "Productivity", "Technology", "Gadgets", "AI & Robotics",
  "Apps & Software", "Photography", "Videography", "Gaming", "Esports",
  "Virtual Reality", "Augmented Reality", "Music", "Dance", "Movies & TV Shows",
  "Comedy", "Memes", "Art", "Illustration", "Drawing & Painting", "Literature",
  "Book Reviews", "Theater", "Photography Art", "Entrepreneurship", "Startups",
  "Marketing", "Social Media Marketing", "Personal Finance", "Investing",
  "Cryptocurrency", "Stock Market", "Business Advice", "Career Advice", "Sports",
  "Football", "Basketball", "Cricket", "Tennis", "Running", "Yoga", "Meditation",
  "Adventure", "Hiking", "Camping", "Extreme Sports", "Surfing", "Skateboarding",
  "Science Education", "Technology Education", "Math Tutorials", "Language Learning",
  "History Education", "Cultural Education", "Online Courses", "Skill Sharing",
  "DIY Education", "Pets", "Dogs", "Cats", "Exotic Animals", "Cars & Automotive",
  "Motorcycles", "Luxury Cars", "DIY & Crafts", "Event Planning", "Wedding Planning",
  "Gardening", "Eco-Friendly Living", "Sustainable Fashion", "Home Renovation",
  "Board Games", "Collectibles", "Tech Reviews", "Unboxing", "ASMR", "Vlogging",
  "Challenges", "Motivational Speaking", "Activism", "Politics", "Spirituality",
  "Mental Health", "Food Challenges", "Recipe Tutorials", "Street Food",
  "Fitness Challenges", "Workout Tutorials", "Nutrition", "Diet & Weight Loss",
  "Supplements", "Beauty Tutorials", "Makeup Challenges", "Luxury Travel",
  "Backpacking", "Solo Travel", "Family Travel", "Influencer Collaborations",
  "Product Reviews"
];