import Footer from '@/components/home3/Footer';
import { Shield, FileText, CheckCircle, AlertTriangle, Scale, Globe } from 'lucide-react';

export default function TermsAndConditions() {
  const sections = [
    {
      icon: FileText,
      title: "Electronic Record",
      content: "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures."
    },
    {
      icon: Globe,
      title: "Publication",
      content: "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name http://getcreator.online ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform')."
    },
    {
      icon: Shield,
      title: "Platform Ownership",
      content: "The Platform is owned by SITEGALLERIA PRIVATE LIMITED, a company incorporated under the Companies Act, 1956 with its registered office at 7, 2nd main, 3rd phase, JP Nagar, Bangalore, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our')."
    }
  ];

  const terms = [
    {
      number: "1",
      text: "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform."
    },
    {
      number: "2",
      text: "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law."
    },
    {
      number: "3",
      text: "Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements."
    },
    {
      number: "4",
      text: "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics."
    },
    {
      number: "5",
      text: "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws."
    },
    {
      number: "6",
      text: "You agree to pay us the charges associated with availing the Services."
    },
    {
      number: "7",
      text: "You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you."
    },
    {
      number: "8",
      text: "You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information."
    },
    {
      number: "9",
      text: "You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services."
    },
    {
      number: "10",
      text: "You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party."
    },
    {
      number: "11",
      text: "Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event."
    },
    {
      number: "12",
      text: "These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India."
    },
    {
      number: "13",
      text: "All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Bangalore and Karnataka."
    },
    {
      number: "14",
      text: "All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website."
    }
  ];

  return (
    <>
    <div className="min-h-screen bg-[#0D0D1A] relative overflow-hidden">
      {/* Animated Background */}
      <div className="absolute top-20 left-20 w-96 h-96 bg-purple-500/20 rounded-full blur-[120px] animate-pulse"></div>
      <div className="absolute bottom-20 right-20 w-96 h-96 bg-blue-500/20 rounded-full blur-[120px] animate-pulse"></div>
      <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-pink-500/10 rounded-full blur-[120px]"></div>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20 relative z-10">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500 rounded-2xl mb-6 shadow-lg">
            <Scale className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500 bg-clip-text text-transparent mb-4">
            Terms & Conditions
          </h1>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto">
            Please read these terms and conditions carefully before using our platform
          </p>
        </div>

        {/* Important Notice */}
        <div className="backdrop-blur-xl bg-amber-500/10 border border-amber-500/20 rounded-2xl p-6 mb-8">
          <div className="flex items-start gap-4">
            <AlertTriangle className="w-6 h-6 text-amber-400 flex-shrink-0 mt-1" />
            <div>
              <h3 className="text-xl font-bold text-amber-300 mb-2">Important Notice</h3>
              <p className="text-amber-200/90 leading-relaxed">
                Your use of the Platform and services and tools are governed by the following terms and conditions as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions constitute Your binding obligations.
              </p>
            </div>
          </div>
        </div>

        {/* Agreement Warning */}
        <div className="backdrop-blur-xl bg-blue-500/10 border border-blue-500/20 rounded-2xl p-6 mb-8">
          <div className="flex items-start gap-4">
            <CheckCircle className="w-6 h-6 text-blue-400 flex-shrink-0 mt-1" />
            <div>
              <p className="text-blue-200 font-semibold text-lg leading-relaxed">
                ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
              </p>
            </div>
          </div>
        </div>

        {/* Introduction Sections */}
        <div className="space-y-6 mb-12">
          {sections.map((section, index) => {
            const Icon = section.icon;
            return (
              <div
                key={index}
                className="backdrop-blur-xl bg-white/5 rounded-2xl p-6 border border-white/10 hover:border-purple-500/30 transition-all duration-300"
              >
                <div className="flex items-start gap-4">
                  <div className="w-12 h-12 bg-gradient-to-br from-pink-500/20 to-purple-500/20 rounded-xl flex items-center justify-center flex-shrink-0 border border-purple-500/20">
                    <Icon className="w-6 h-6 text-purple-400" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-white mb-3">{section.title}</h3>
                    <p className="text-gray-300 leading-relaxed">{section.content}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Additional Context */}
        <div className="backdrop-blur-xl bg-white/5 rounded-2xl p-6 border border-white/10 mb-8">
          <p className="text-gray-300 leading-relaxed mb-4">
            For the purpose of these Terms of Use, wherever the context so requires <span className="text-pink-400 font-semibold">'you', 'your' or 'user'</span> shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
          <p className="text-gray-300 leading-relaxed">
            These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
          </p>
        </div>

        {/* Terms List Header */}
        <div className="backdrop-blur-xl bg-gradient-to-r from-pink-500/10 via-purple-500/10 to-blue-500/10 border border-purple-500/20 rounded-2xl p-6 mb-8">
          <h2 className="text-2xl font-bold text-white mb-2">Terms of Service</h2>
          <p className="text-gray-300">
            The use of Platform and/or availing of our Services is subject to the following Terms of Use:
          </p>
        </div>

        {/* Terms List */}
        <div className="space-y-4 mb-12">
          {terms.map((term) => (
            <div
              key={term.number}
              className="backdrop-blur-xl bg-white/5 rounded-2xl p-6 border border-white/10 hover:border-purple-500/30 transition-all duration-300 group"
            >
              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-gradient-to-br from-pink-500 to-purple-500 rounded-xl flex items-center justify-center font-bold text-white shadow-lg group-hover:shadow-purple-500/50 transition-all duration-300">
                    {term.number}
                  </div>
                </div>
                <div className="flex-1">
                  <p className="text-gray-300 leading-relaxed">{term.text}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer Contact */}
        <div className="backdrop-blur-xl bg-gradient-to-br from-blue-500/10 to-purple-500/10 border border-blue-500/20 rounded-2xl p-8 text-center">
          <h3 className="text-xl font-bold text-white mb-3">Need Help?</h3>
          <p className="text-gray-300 mb-6">
            If you have any questions or concerns about these Terms & Conditions, please contact us using the information provided on our website.
          </p>
          <a
            href="mailto:support@getcreator.online"
            className="inline-flex items-center gap-2 bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500 text-white font-semibold px-8 py-3 rounded-xl hover:shadow-[0_0_30px_rgba(168,85,247,0.5)] transition-all duration-300 hover:scale-[1.02] active:scale-[0.98]"
          >
            Contact Support
          </a>
        </div>

        {/* Last Updated */}
        <p className="text-center text-sm text-gray-500 mt-8">
          Last Updated: November 2025
        </p>
      </div>
    </div>
          <Footer />
    </>
  );
}